runtime: nodejs20
env: standard
instance_class: F1 

beta_settings:
  cloud_sql_instances : 'silent-fuze-400506:asia-southeast2:signup-login-auth'

handlers:
- url: /.*
  script: auto
  secure: always  # Enforce HTTPS for all requests