runtime: nodejs20
env: standard
instance_class: F1 

env_variables:
  cloud_storage_bucket : 'dataset-bucket-9801'

beta_settings:
  cloud_sql_instances : 'silent-fuze-400506:us-central1:signup-login-auth'


handlers:
- url: /.*
  script: auto
  secure: always  # Enforce HTTPS for all requests